name: Code Coverage
on:
  push:

jobs:
  codecov:
    name: codecov
    runs-on: unbuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
